#include<bits/stdc++.h>
using namespace std;
int t,m;
int a,b,c,d;
int xp,xq,yp,yq,z;
int main()
{
    freopen("uqe.in","r",stdin);
    freopen("uqe.out","w",stdout);
    ios::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
    cin>>t>>m;
    while(t--)
    {
        cin>>a>>b>>c;
        d=b*b-4*a*c;
        if(d<0)
        {
            cout<<"NO"<<endl;
            continue;
        }
        xp=-b;
        xq=2*a;
        yp=1;
        yq=2*a;
        z=d;
        if(xq<0)
        {
            xq*=-1;
            xp*=-1;
        }
        if(yq<0)
        {
            yq*=-1;
        }
        if(yp<0)
        {
            yp*=-1;
        }
        for(int i=2;i*i<=d;i++)
        {
            while(z%(i*i)==0)
            {
                yp*=i;
                z/=i*i;
            }
        }
        if(z==1)
        {
            xp+=yp;
            z=0;yp=0;yq=0;
        }
        if(xp&&xq&&xp%xq==0)
        {
            xp/=xq;
            xq=0;
        }
        else
        {
            for(int i=2;i<=xq;i++)
            {
                while(xq%i==0&&xp%i==0)
                {
                    xq/=i;
                    xp/=i;
                }
            }
        }
        if(yp&&yq&&yp%yq==0)
        {
            yp/=yq;
            yq=0;
        }
        else
        {
            for(int i=2;i<=yq;i++)
            {
                while(yq%i==0&&yp%i==0)
                {
                    yq/=i;
                    yp/=i;
                }
            }
        }
        //cout<<xp<<" "<<xq<<" "<<yp<<" "<<yq<<" "<<z<<endl;
        if(xp!=0)
        {
            cout<<xp;
            if(xq&&xq!=1)
            {
                cout<<"/"<<xq;
            }
            if(z!=0)
            {
                cout<<"+";
            }
        }
        if(z!=0)
        {
            if(yp&&yp!=1)
            {
                cout<<yp<<"*";
            }
            cout<<"sqrt("<<z<<")";
            if(yq&&yq!=1)
            {
                cout<<"/"<<yq;
            }
        }
        cout<<endl;
    }
    return 0;
}
